services:
  backend-web:
    image: xianyu-backend-web:gamer520-v0.2.3
    pull_policy: never
    environment:
      VERSION: "0.2.3"

  frontend:
    image: xianyu-frontend:gamer520-v0.2.2
    pull_policy: never
