services:
  backend-web:
    image: xianyu-backend-web:gamer520-v0.2.1
    pull_policy: never
    environment:
      VERSION: "0.2.1"

  frontend:
    image: xianyu-frontend:gamer520-v0.2.1
    pull_policy: never
