import { useEffect, useState } from 'react'
import { Button, Form, Input, InputNumber, Select, Switch, Table, type TableColumnProps } from '@arco-design/web-react'
import { Heart, MapPin, Search, ShoppingBag } from 'lucide-react'
import { getAccounts } from '@/api/accounts'
import {
  generateInteractionCommentDraft,
  publishInteractionComment,
  searchItems,
  type SearchResultItem,
} from '@/api/search'
import { useAuthStore } from '@/store/authStore'
import { useUIStore } from '@/store/uiStore'
import { PageLoading, ButtonLoading } from '@/components/common/Loading'
import type { Account } from '@/types'

type DraftMap = Record<string, string>
type LoadingMap = Record<string, boolean>
type ReviewedMap = Record<string, boolean>
type SearchResultRow = SearchResultItem & { _rowKey: string }
type InteractionCache = {
  selectedAccount: string
  keyword: string
  wordCount: number
  tone: 'friendly' | 'question' | 'concise'
  includeDetail: boolean
  autoGenerateDrafts: boolean
  batchLimit: number
  results: SearchResultItem[]
  total: number
  drafts: DraftMap
  reviewed: ReviewedMap
}

const CACHE_KEY = 'xianyu:item-interaction-assistant:v1'

export function ItemInteractionAssistant() {
  const { addToast } = useUIStore()
  const { isAuthenticated, token, _hasHydrated } = useAuthStore()
  const [accounts, setAccounts] = useState<Account[]>([])
  const [selectedAccount, setSelectedAccount] = useState('')
  const [keyword, setKeyword] = useState('')
  const [wordCount, setWordCount] = useState(30)
  const [tone, setTone] = useState<'friendly' | 'question' | 'concise'>('question')
  const [includeDetail, setIncludeDetail] = useState(true)
  const [autoGenerateDrafts, setAutoGenerateDrafts] = useState(false)
  const [batchLimit, setBatchLimit] = useState(5)
  const [loading, setLoading] = useState(true)
  const [searching, setSearching] = useState(false)
  const [batchGenerating, setBatchGenerating] = useState(false)
  const [results, setResults] = useState<SearchResultItem[]>([])
  const [total, setTotal] = useState(0)
  const [drafts, setDrafts] = useState<DraftMap>({})
  const [draftLoading, setDraftLoading] = useState<LoadingMap>({})
  const [commentLoading, setCommentLoading] = useState<LoadingMap>({})
  const [reviewed, setReviewed] = useState<ReviewedMap>({})
  const [cacheReady, setCacheReady] = useState(false)

  useEffect(() => {
    try {
      const cached = localStorage.getItem(CACHE_KEY)
      if (!cached) {
        setCacheReady(true)
        return
      }

      const data = JSON.parse(cached) as Partial<InteractionCache>
      setSelectedAccount(data.selectedAccount || '')
      setKeyword(data.keyword || '')
      setWordCount(Number(data.wordCount || 30))
      setTone(data.tone || 'question')
      setIncludeDetail(data.includeDetail ?? true)
      setAutoGenerateDrafts(Boolean(data.autoGenerateDrafts))
      setBatchLimit(Number(data.batchLimit || 5))
      setResults(Array.isArray(data.results) ? data.results : [])
      setTotal(Number(data.total || 0))
      setDrafts(data.drafts || {})
      setReviewed(data.reviewed || {})
    } catch {
      localStorage.removeItem(CACHE_KEY)
    } finally {
      setCacheReady(true)
    }
  }, [])

  useEffect(() => {
    if (!cacheReady) return
    const cache: InteractionCache = {
      selectedAccount,
      keyword,
      wordCount,
      tone,
      includeDetail,
      autoGenerateDrafts,
      batchLimit,
      results,
      total,
      drafts,
      reviewed,
    }
    localStorage.setItem(CACHE_KEY, JSON.stringify(cache))
  }, [autoGenerateDrafts, batchLimit, cacheReady, drafts, includeDetail, keyword, results, reviewed, selectedAccount, tone, total, wordCount])

  useEffect(() => {
    if (!_hasHydrated || !isAuthenticated || !token) return
    ;(async () => {
      try {
        setLoading(true)
        const data = await getAccounts()
        setAccounts(data)
        if (data.length > 0) setSelectedAccount((current) => current || data[0].id)
      } catch {
        addToast({ type: 'error', message: '加载账号失败' })
      } finally {
        setLoading(false)
      }
    })()
  }, [_hasHydrated, isAuthenticated, token])

  const getItemKey = (item: SearchResultItem, index: number) => item.item_id || `${item.title}-${index}`

  const handleSearch = async (event?: React.FormEvent) => {
    event?.preventDefault()
    if (!keyword.trim()) {
      addToast({ type: 'warning', message: '请输入搜索关键词' })
      return
    }
    if (!selectedAccount) {
      addToast({ type: 'warning', message: '请先选择账号' })
      return
    }

    setSearching(true)
    setResults([])
    setDrafts({})
    setReviewed({})
    try {
      const result = await searchItems(keyword.trim(), 1, 12, selectedAccount)
      if (!result.success) {
        addToast({ type: 'error', message: result.error || '搜索失败' })
        return
      }
      const data = result.data || []
      setResults(data)
      setTotal(result.total || data.length)
      if (data.length === 0) {
        addToast({ type: 'info', message: '未找到相关商品' })
      } else if (autoGenerateDrafts) {
        await generateDraftsForItems(data.slice(0, batchLimit))
      }
    } catch {
      addToast({ type: 'error', message: '搜索失败，请稍后重试' })
    } finally {
      setSearching(false)
    }
  }

  const handleGenerateDraft = async (item: SearchResultItem, index: number) => {
    if (!selectedAccount) {
      addToast({ type: 'warning', message: '请先选择账号' })
      return
    }

    const key = getItemKey(item, index)
    setDraftLoading((prev) => ({ ...prev, [key]: true }))
    try {
      const result = await generateInteractionCommentDraft({
        cookie_id: selectedAccount,
        item,
        word_count: wordCount,
        tone,
        include_detail: includeDetail,
      })
      setDrafts((prev) => ({ ...prev, [key]: result.draft || '' }))
      const totalTokens = result.usage?.total_tokens
      addToast({
        type: 'success',
        message: totalTokens ? `草稿已生成，本次约 ${totalTokens} Token` : '草稿已生成',
      })
    } catch (error) {
      const detail = (error as { response?: { data?: { detail?: string } } })?.response?.data?.detail
      addToast({ type: 'error', message: detail || '生成草稿失败，请检查 AI 设置' })
    } finally {
      setDraftLoading((prev) => ({ ...prev, [key]: false }))
    }
  }

  const generateDraftsForItems = async (items: SearchResultItem[]) => {
    if (!selectedAccount) {
      addToast({ type: 'warning', message: '请先选择账号' })
      return
    }
    if (items.length === 0) return

    setBatchGenerating(true)
    let successCount = 0
    try {
      for (const [index, item] of items.entries()) {
        const key = getItemKey(item, index)
        if (drafts[key]) continue

        setDraftLoading((prev) => ({ ...prev, [key]: true }))
        try {
          const result = await generateInteractionCommentDraft({
            cookie_id: selectedAccount,
            item,
            word_count: wordCount,
            tone,
            include_detail: includeDetail,
          })
          setDrafts((prev) => ({ ...prev, [key]: result.draft || '' }))
          successCount += 1
        } finally {
          setDraftLoading((prev) => ({ ...prev, [key]: false }))
        }
      }
      addToast({ type: 'success', message: `已生成 ${successCount} 条评论草稿` })
    } catch (error) {
      const detail = (error as { response?: { data?: { detail?: string } } })?.response?.data?.detail
      addToast({ type: 'error', message: detail || '批量生成草稿失败，请检查 AI 设置' })
    } finally {
      setBatchGenerating(false)
    }
  }

  const handleBatchGenerate = async () => {
    await generateDraftsForItems(results.slice(0, batchLimit))
  }

  const handleClearCache = () => {
    localStorage.removeItem(CACHE_KEY)
    setKeyword('')
    setResults([])
    setTotal(0)
    setDrafts({})
    setReviewed({})
    addToast({ type: 'success', message: '缓存已清除' })
  }

  const handleCopyAndOpen = async (text: string, itemUrl: string) => {
    if (!text) return
    await navigator.clipboard.writeText(text)
    window.open(itemUrl, '_blank', 'noopener,noreferrer')
    addToast({ type: 'success', message: '草稿已复制，请在商品页手动点击评论并粘贴确认' })
  }

  const handlePublishComment = async (item: SearchResultItem, index: number, draft?: string) => {
    const comment = (draft || '').trim()
    if (!selectedAccount) {
      addToast({ type: 'warning', message: '请先选择账号' })
      return
    }
    if (!comment) {
      addToast({ type: 'warning', message: '请先生成评论草稿' })
      return
    }

    const key = getItemKey(item, index)
    setCommentLoading((prev) => ({ ...prev, [key]: true }))
    try {
      await publishInteractionComment({
        cookie_id: selectedAccount,
        item,
        comment,
      })
      setReviewed((prev) => ({ ...prev, [key]: true }))
      addToast({ type: 'success', message: '评论已提交' })
    } catch (error) {
      const detail = (error as { response?: { data?: { detail?: string } } })?.response?.data?.detail
      addToast({ type: 'error', message: detail || '评论提交失败，请检查账号状态或稍后重试' })
    } finally {
      setCommentLoading((prev) => ({ ...prev, [key]: false }))
    }
  }

  if (loading) {
    return <PageLoading />
  }

  const renderActions = (item: SearchResultItem, index: number, itemKey: string, itemUrl: string, draft?: string, compact = false) => (
    <div className={compact ? 'flex w-[132px] shrink-0 flex-col gap-2' : 'mt-3 flex flex-wrap gap-2'}>
      <Button
        type="primary"
        size="small"
        loading={draftLoading[itemKey]}
        onClick={() => handleGenerateDraft(item, index)}
        className="inline-flex items-center justify-center"
      >
        生成草稿
      </Button>
      {draft && !compact && (
        <Button
          size="small"
          status="success"
          loading={commentLoading[itemKey]}
          onClick={() => handlePublishComment(item, index, draft)}
          className="inline-flex items-center justify-center"
        >
          点击评论
        </Button>
      )}
      {draft && !compact && (
        <Button
          size="small"
          onClick={() => handleCopyAndOpen(draft, itemUrl)}
          className="inline-flex items-center justify-center"
        >
          复制备用
        </Button>
      )}
      <Button
        size="small"
        onClick={() => window.open(itemUrl, '_blank', 'noopener,noreferrer')}
        className="inline-flex items-center justify-center"
      >
        打开商品
      </Button>
      <Button
        size="small"
        status={reviewed[itemKey] ? 'success' : 'default'}
        onClick={() => setReviewed((prev) => ({ ...prev, [itemKey]: !prev[itemKey] }))}
        className="inline-flex items-center justify-center"
      >
        {reviewed[itemKey] ? '已评论' : '标记已评论'}
      </Button>
    </div>
  )

  const tableData: SearchResultRow[] = results.map((item, index) => ({
    ...item,
    _rowKey: getItemKey(item, index),
  }))

  const tableColumns: TableColumnProps<SearchResultRow>[] = [
    {
      title: '商品',
      dataIndex: 'title',
      width: 420,
      render: (_value, item, index) => (
        <div className="flex items-center gap-3">
          <div className="h-16 w-16 shrink-0 overflow-hidden rounded-[8px] bg-slate-100 dark:bg-slate-800">
            {item.main_image ? (
              <img src={item.main_image} alt={item.title} className="h-full w-full object-cover" />
            ) : (
              <div className="flex h-full w-full items-center justify-center text-slate-300">
                <ShoppingBag className="h-7 w-7" />
              </div>
            )}
          </div>
          <div className="min-w-0">
            <div className="line-clamp-2 font-medium text-slate-900 dark:text-slate-100">{item.title}</div>
            <div className="mt-1 text-xs text-slate-400">ID: {item.item_id || index + 1}</div>
          </div>
        </div>
      ),
    },
    {
      title: '价格',
      dataIndex: 'price',
      width: 110,
      render: (value) => <span className="font-semibold text-red-500">{value || '-'}</span>,
    },
    {
      title: '想要',
      dataIndex: 'want_count',
      width: 120,
      render: (value) => value ? (
        <span className="inline-flex items-center text-slate-500">
          <Heart className="mr-1 h-3.5 w-3.5" />
          {value}
        </span>
      ) : '-',
    },
    {
      title: '地区',
      dataIndex: 'area',
      width: 100,
      render: (value) => value ? (
        <span className="inline-flex items-center text-slate-500">
          <MapPin className="mr-1 h-3.5 w-3.5" />
          {value}
        </span>
      ) : '-',
    },
    {
      title: '草稿',
      width: 260,
      render: (_value, item, index) => {
        const key = getItemKey(item, index)
        const draft = drafts[key]
        if (!draft) return <span className="text-slate-400">未生成</span>
        return <span className="line-clamp-2 text-sm text-slate-600 dark:text-slate-300">{draft}</span>
      },
    },
    {
      title: '操作',
      width: 360,
      fixed: 'right',
      render: (_value, item, index) => {
        const key = getItemKey(item, index)
        const draft = drafts[key]
        const itemUrl = item.item_url || `https://www.goofish.com/item?id=${item.item_id}`
        return renderActions(item, index, key, itemUrl, draft)
      },
    },
  ]

  return (
    <div className="space-y-4">
      <div className="vben-card">
        <div className="accounts-page-intro">
          <h1>AI 评论草稿助手</h1>
          <p>按关键词搜索商品，AI 自动生成一句评论；点击评论后使用所选账号提交到商品页。</p>
        </div>

        <div className="rounded-[8px] border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-700 dark:border-amber-500/30 dark:bg-amber-500/10 dark:text-amber-300">
          评论只会在你点击“点击评论”后提交；请先检查 AI 生成内容，避免重复或无关评论。
        </div>

        <Form layout="vertical" className="mt-4">
          <div className="grid grid-cols-1 gap-4 lg:grid-cols-6">
            <Form.Item label="使用账号">
              <Select
                value={selectedAccount}
                onChange={setSelectedAccount}
                placeholder="请选择账号"
                options={accounts.map((account) => ({ label: account.id, value: account.id }))}
              />
            </Form.Item>
            <Form.Item label="草稿字数">
              <InputNumber
                min={10}
                max={80}
                value={wordCount}
                onChange={(value) => setWordCount(Number(value || 30))}
                style={{ width: '100%' }}
              />
            </Form.Item>
            <Form.Item label="草稿风格">
              <Select
                value={tone}
                onChange={(value) => setTone(value as 'friendly' | 'question' | 'concise')}
                options={[
                  { label: '真实咨询', value: 'question' },
                  { label: '友好自然', value: 'friendly' },
                  { label: '简短克制', value: 'concise' },
                ]}
              />
            </Form.Item>
            <Form.Item label="详情策略">
              <div className="flex h-8 items-center gap-2">
                <Switch checked={includeDetail} onChange={setIncludeDetail} />
                <span className="text-sm text-slate-500">详情较短时纳入</span>
              </div>
            </Form.Item>
            <Form.Item label="搜索后自动生成">
              <div className="flex h-8 items-center gap-2">
                <Switch checked={autoGenerateDrafts} onChange={setAutoGenerateDrafts} />
                <span className="text-sm text-slate-500">仅生成草稿</span>
              </div>
            </Form.Item>
            <Form.Item label="批量数量">
              <InputNumber
                min={1}
                max={12}
                value={batchLimit}
                onChange={(value) => setBatchLimit(Number(value || 5))}
                style={{ width: '100%' }}
              />
            </Form.Item>
          </div>
        </Form>

        <form onSubmit={handleSearch} className="mt-5 flex flex-col gap-3 md:flex-row">
          <div className="relative flex-1">
            <Search className="absolute left-4 top-1/2 z-10 h-4 w-4 -translate-y-1/2 text-slate-400" />
            <Input
              value={keyword}
              onChange={setKeyword}
              placeholder="输入关键词搜索商品..."
              className="pl-10"
            />
          </div>
          <Button type="primary" htmlType="submit" loading={searching}>
            搜索商品
          </Button>
          <Button disabled={results.length === 0} loading={batchGenerating} onClick={handleBatchGenerate}>
            批量生成草稿
          </Button>
          <Button disabled={!keyword && results.length === 0} onClick={handleClearCache}>
            清除缓存
          </Button>
        </form>

        <div className="my-5 text-sm text-slate-500">
          {total > 0 ? `搜索结果：${total} 件，当前最多批量生成前 ${batchLimit} 件的草稿。` : ''}
        </div>

        {searching && (
          <div className="flex items-center justify-center py-12 text-blue-500">
            <ButtonLoading />
            <span className="ml-2">正在搜索中...</span>
          </div>
        )}

        {!searching && results.length === 0 && (
          <div className="py-12 text-center text-slate-500 dark:text-slate-400">
            <ShoppingBag className="mx-auto mb-4 h-16 w-16 text-slate-300 dark:text-slate-600" />
            <p>输入关键词开始搜索</p>
          </div>
        )}

        {results.length > 0 && (
          <Table
            rowKey="_rowKey"
            columns={tableColumns}
            data={tableData}
            pagination={false}
            border={false}
            scroll={{ x: 1360 }}
          />
        )}
      </div>
    </div>
  )
}
